### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by zmhawk** [Hopkins1/TradSimpChinese#10]
当我用该工具将一本电子书从繁体转到简体时，它崩溃了，下面是错误信息

```
Traceback (most recent call last):
  File "calibre_plugins.chinese_text.main", line 128, in dispatcher
  File "calibre_plugins.chinese_text.main", line 174, in process_files
  File "calibre_plugins.chinese_text.main", line 367, in set_metadata_toc
  File "calibre_plugins.chinese_text.resources.opencc_python.opencc", line 70, in convert
TypeError: expected string or buffer
```

经过多次排除尝试后，大概确定了引起错误的位置

这是删减后的最小的 [测试文件](https://cdn.undor.cn/TradSimpChinese-test.epub)，出错位置在  `/OEBPS/Text/nav.xhtml`

**Comment by Hopkins1** [comment]
New release 2.3.4
