### ISSUE TITLE
Failed to convert Chinese for calibre, version 3.4.0

### ISSUE THREAD

**Issue by siutsin** [Hopkins1/TradSimpChinese#3]
Hi, I am getting this error when converting the entire epub. However, if I select and open an individual HTML, I am able to convert. Is there a way to select multiple HTML in the list and convert?

```
calibre, version 3.4.0
錯誤： 失敗: Failed to convert Chinese, click "Show details" for more info

Traceback (most recent call last):
  File "calibre_plugins.chinese_text.main", line 109, in dispatcher
  File "calibre_plugins.chinese_text.main", line 154, in process_files
  File "calibre_plugins.chinese_text.main", line 285, in set_metadata_toc
  File "calibre_plugins.chinese_text.resources.opencc_python.opencc", line 74, in convert
TypeError: expected string or buffer
```

**Comment by Hopkins1** [comment]
It looks like the plugin has a problem the text contents of one of the OPF file fields. It must be the text in one or more of these tags:

dc:title
dc:description
dc:publisher
dc:subject
dc:contributor
dc:coverage
dc:rights

In order to debug this:

1. Select the opf file (or whatever file that contains the above tags) in the file browser panel on the left side of the editor. This will be in the Miscellaneous section of the browser panel.
2. Completely remove one of these tag entries (start tag, text, and end tag)
3. Re-run the plugin for the entire epub
4. Keep removing/re-adding tags until the problem tags are found

Eventually the problem should go away. I need to see the tag (or tags)  and text that is causing the problem. Be sure to keep a backup copy of the book before trying this!

If that's not possible, just send me a copy of the contents of the opf file. I'll take a look at it.

Thanks!

**Comment by ayeteng** [comment]
I have similar issue on Calibre 3.6.0

Traceback (most recent call last):
  File "calibre_plugins.chinese_text.main", line 109, in dispatcher
  File "calibre_plugins.chinese_text.main", line 154, in process_files
  File "calibre_plugins.chinese_text.main", line 285, in set_metadata_toc
  File "calibre_plugins.chinese_text.resources.opencc_python.opencc", line 74, in convert
TypeError: expected string or buffer

Change the txt to opf from below
[fb.txt](https://github.com/Hopkins1/TradSimpChinese/files/1202114/fb.txt)

Can you help?

**Comment by Hopkins1** [comment]
I added a fix to check for an empty tag and verified it fixed the problem. Use new release 2.1.1
